// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/parsers/bitcom.proto

package parsers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BitcomData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocols     []*BitcomProtocol      `protobuf:"bytes,1,rep,name=protocols,proto3" json:"protocols,omitempty"`
	ScriptPrefix  []byte                 `protobuf:"bytes,2,opt,name=script_prefix,json=scriptPrefix,proto3" json:"script_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BitcomData) Reset() {
	*x = BitcomData{}
	mi := &file_proto_parsers_bitcom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BitcomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitcomData) ProtoMessage() {}

func (x *BitcomData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsers_bitcom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitcomData.ProtoReflect.Descriptor instead.
func (*BitcomData) Descriptor() ([]byte, []int) {
	return file_proto_parsers_bitcom_proto_rawDescGZIP(), []int{0}
}

func (x *BitcomData) GetProtocols() []*BitcomProtocol {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *BitcomData) GetScriptPrefix() []byte {
	if x != nil {
		return x.ScriptPrefix
	}
	return nil
}

type BitcomProtocol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Script        []byte                 `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Pos           uint32                 `protobuf:"varint,3,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BitcomProtocol) Reset() {
	*x = BitcomProtocol{}
	mi := &file_proto_parsers_bitcom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BitcomProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitcomProtocol) ProtoMessage() {}

func (x *BitcomProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsers_bitcom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitcomProtocol.ProtoReflect.Descriptor instead.
func (*BitcomProtocol) Descriptor() ([]byte, []int) {
	return file_proto_parsers_bitcom_proto_rawDescGZIP(), []int{1}
}

func (x *BitcomProtocol) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *BitcomProtocol) GetScript() []byte {
	if x != nil {
		return x.Script
	}
	return nil
}

func (x *BitcomProtocol) GetPos() uint32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

type BData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaType     string                 `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Encoding      string                 `protobuf:"bytes,2,opt,name=encoding,proto3" json:"encoding,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BData) Reset() {
	*x = BData{}
	mi := &file_proto_parsers_bitcom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BData) ProtoMessage() {}

func (x *BData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsers_bitcom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BData.ProtoReflect.Descriptor instead.
func (*BData) Descriptor() ([]byte, []int) {
	return file_proto_parsers_bitcom_proto_rawDescGZIP(), []int{2}
}

func (x *BData) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *BData) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *BData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BData) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type MapData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Values        []string               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapData) Reset() {
	*x = MapData{}
	mi := &file_proto_parsers_bitcom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapData) ProtoMessage() {}

func (x *MapData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsers_bitcom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapData.ProtoReflect.Descriptor instead.
func (*MapData) Descriptor() ([]byte, []int) {
	return file_proto_parsers_bitcom_proto_rawDescGZIP(), []int{3}
}

func (x *MapData) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *MapData) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *MapData) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type AipData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AipData) Reset() {
	*x = AipData{}
	mi := &file_proto_parsers_bitcom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AipData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AipData) ProtoMessage() {}

func (x *AipData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsers_bitcom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AipData.ProtoReflect.Descriptor instead.
func (*AipData) Descriptor() ([]byte, []int) {
	return file_proto_parsers_bitcom_proto_rawDescGZIP(), []int{4}
}

func (x *AipData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AipData) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type BapData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BapData) Reset() {
	*x = BapData{}
	mi := &file_proto_parsers_bitcom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BapData) ProtoMessage() {}

func (x *BapData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsers_bitcom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BapData.ProtoReflect.Descriptor instead.
func (*BapData) Descriptor() ([]byte, []int) {
	return file_proto_parsers_bitcom_proto_rawDescGZIP(), []int{5}
}

func (x *BapData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SigmaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Vin           uint32                 `protobuf:"varint,4,opt,name=vin,proto3" json:"vin,omitempty"`
	Valid         bool                   `protobuf:"varint,5,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigmaData) Reset() {
	*x = SigmaData{}
	mi := &file_proto_parsers_bitcom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigmaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigmaData) ProtoMessage() {}

func (x *SigmaData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsers_bitcom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigmaData.ProtoReflect.Descriptor instead.
func (*SigmaData) Descriptor() ([]byte, []int) {
	return file_proto_parsers_bitcom_proto_rawDescGZIP(), []int{6}
}

func (x *SigmaData) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *SigmaData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SigmaData) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SigmaData) GetVin() uint32 {
	if x != nil {
		return x.Vin
	}
	return 0
}

func (x *SigmaData) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_proto_parsers_bitcom_proto protoreflect.FileDescriptor

const file_proto_parsers_bitcom_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/parsers/bitcom.proto\x12\x0eonesat.parsers\"o\n" +
	"\n" +
	"BitcomData\x12<\n" +
	"\tprotocols\x18\x01 \x03(\v2\x1e.onesat.parsers.BitcomProtocolR\tprotocols\x12#\n" +
	"\rscript_prefix\x18\x02 \x01(\fR\fscriptPrefix\"V\n" +
	"\x0eBitcomProtocol\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06script\x18\x02 \x01(\fR\x06script\x12\x10\n" +
	"\x03pos\x18\x03 \x01(\rR\x03pos\"r\n" +
	"\x05BData\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tR\tmediaType\x12\x1a\n" +
	"\bencoding\x18\x02 \x01(\tR\bencoding\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\"G\n" +
	"\aMapData\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\"9\n" +
	"\aAipData\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\"\x1d\n" +
	"\aBapData\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"\x89\x01\n" +
	"\tSigmaData\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x10\n" +
	"\x03vin\x18\x04 \x01(\rR\x03vin\x12\x14\n" +
	"\x05valid\x18\x05 \x01(\bR\x05validB/Z-github.com/b-open-io/1sat-stack/proto/parsersb\x06proto3"

var (
	file_proto_parsers_bitcom_proto_rawDescOnce sync.Once
	file_proto_parsers_bitcom_proto_rawDescData []byte
)

func file_proto_parsers_bitcom_proto_rawDescGZIP() []byte {
	file_proto_parsers_bitcom_proto_rawDescOnce.Do(func() {
		file_proto_parsers_bitcom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_parsers_bitcom_proto_rawDesc), len(file_proto_parsers_bitcom_proto_rawDesc)))
	})
	return file_proto_parsers_bitcom_proto_rawDescData
}

var file_proto_parsers_bitcom_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_parsers_bitcom_proto_goTypes = []any{
	(*BitcomData)(nil),     // 0: onesat.parsers.BitcomData
	(*BitcomProtocol)(nil), // 1: onesat.parsers.BitcomProtocol
	(*BData)(nil),          // 2: onesat.parsers.BData
	(*MapData)(nil),        // 3: onesat.parsers.MapData
	(*AipData)(nil),        // 4: onesat.parsers.AipData
	(*BapData)(nil),        // 5: onesat.parsers.BapData
	(*SigmaData)(nil),      // 6: onesat.parsers.SigmaData
}
var file_proto_parsers_bitcom_proto_depIdxs = []int32{
	1, // 0: onesat.parsers.BitcomData.protocols:type_name -> onesat.parsers.BitcomProtocol
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_parsers_bitcom_proto_init() }
func file_proto_parsers_bitcom_proto_init() {
	if File_proto_parsers_bitcom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_parsers_bitcom_proto_rawDesc), len(file_proto_parsers_bitcom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_parsers_bitcom_proto_goTypes,
		DependencyIndexes: file_proto_parsers_bitcom_proto_depIdxs,
		MessageInfos:      file_proto_parsers_bitcom_proto_msgTypes,
	}.Build()
	File_proto_parsers_bitcom_proto = out.File
	file_proto_parsers_bitcom_proto_goTypes = nil
	file_proto_parsers_bitcom_proto_depIdxs = nil
}
