syntax = "proto3";

package onesat.parsers;

option go_package = "github.com/b-open-io/1sat-engine/proto/parsers";

message BitcomData {
  repeated BitcomProtocol protocols = 1;
  bytes script_prefix = 2;
}

message BitcomProtocol {
  string protocol = 1;
  bytes script = 2;
  uint32 pos = 3;
}

message BData {
  string media_type = 1;
  string encoding = 2;
  bytes data = 3;
  string filename = 4;
}

message MapData {
  string cmd = 1;
  repeated string keys = 2;
  repeated string values = 3;
}

message AipData {
  string address = 1;
  bool valid = 2;
}

message BapData {
  string type = 1;
}

message SigmaData {
  string algorithm = 1;
  string address = 2;
  bytes signature = 3;
  uint32 vin = 4;
  bool valid = 5;
}
