// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/parsers/bsv21.proto

package parsers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bsv21Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Symbol        *string                `protobuf:"bytes,3,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	Decimals      *uint32                `protobuf:"varint,4,opt,name=decimals,proto3,oneof" json:"decimals,omitempty"`
	Icon          *string                `protobuf:"bytes,5,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	Amount        uint64                 `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bsv21Data) Reset() {
	*x = Bsv21Data{}
	mi := &file_proto_parsers_bsv21_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bsv21Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bsv21Data) ProtoMessage() {}

func (x *Bsv21Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsers_bsv21_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bsv21Data.ProtoReflect.Descriptor instead.
func (*Bsv21Data) Descriptor() ([]byte, []int) {
	return file_proto_parsers_bsv21_proto_rawDescGZIP(), []int{0}
}

func (x *Bsv21Data) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bsv21Data) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Bsv21Data) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *Bsv21Data) GetDecimals() uint32 {
	if x != nil && x.Decimals != nil {
		return *x.Decimals
	}
	return 0
}

func (x *Bsv21Data) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *Bsv21Data) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_proto_parsers_bsv21_proto protoreflect.FileDescriptor

const file_proto_parsers_bsv21_proto_rawDesc = "" +
	"\n" +
	"\x19proto/parsers/bsv21.proto\x12\x0eonesat.parsers\"\xbb\x01\n" +
	"\tBsv21Data\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x1b\n" +
	"\x06symbol\x18\x03 \x01(\tH\x00R\x06symbol\x88\x01\x01\x12\x1f\n" +
	"\bdecimals\x18\x04 \x01(\rH\x01R\bdecimals\x88\x01\x01\x12\x17\n" +
	"\x04icon\x18\x05 \x01(\tH\x02R\x04icon\x88\x01\x01\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x04R\x06amountB\t\n" +
	"\a_symbolB\v\n" +
	"\t_decimalsB\a\n" +
	"\x05_iconB/Z-github.com/b-open-io/1sat-stack/proto/parsersb\x06proto3"

var (
	file_proto_parsers_bsv21_proto_rawDescOnce sync.Once
	file_proto_parsers_bsv21_proto_rawDescData []byte
)

func file_proto_parsers_bsv21_proto_rawDescGZIP() []byte {
	file_proto_parsers_bsv21_proto_rawDescOnce.Do(func() {
		file_proto_parsers_bsv21_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_parsers_bsv21_proto_rawDesc), len(file_proto_parsers_bsv21_proto_rawDesc)))
	})
	return file_proto_parsers_bsv21_proto_rawDescData
}

var file_proto_parsers_bsv21_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_parsers_bsv21_proto_goTypes = []any{
	(*Bsv21Data)(nil), // 0: onesat.parsers.Bsv21Data
}
var file_proto_parsers_bsv21_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_parsers_bsv21_proto_init() }
func file_proto_parsers_bsv21_proto_init() {
	if File_proto_parsers_bsv21_proto != nil {
		return
	}
	file_proto_parsers_bsv21_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_parsers_bsv21_proto_rawDesc), len(file_proto_parsers_bsv21_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_parsers_bsv21_proto_goTypes,
		DependencyIndexes: file_proto_parsers_bsv21_proto_depIdxs,
		MessageInfos:      file_proto_parsers_bsv21_proto_msgTypes,
	}.Build()
	File_proto_parsers_bsv21_proto = out.File
	file_proto_parsers_bsv21_proto_goTypes = nil
	file_proto_parsers_bsv21_proto_depIdxs = nil
}
