// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/parsers/inscription.proto

package parsers

import (
	parsepb "github.com/b-open-io/1sat-stack/proto/parsepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InscriptionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Parent        *parsepb.OutPoint      `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	ScriptPrefix  []byte                 `protobuf:"bytes,4,opt,name=script_prefix,json=scriptPrefix,proto3" json:"script_prefix,omitempty"`
	ScriptSuffix  []byte                 `protobuf:"bytes,5,opt,name=script_suffix,json=scriptSuffix,proto3" json:"script_suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InscriptionData) Reset() {
	*x = InscriptionData{}
	mi := &file_proto_parsers_inscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InscriptionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InscriptionData) ProtoMessage() {}

func (x *InscriptionData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsers_inscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InscriptionData.ProtoReflect.Descriptor instead.
func (*InscriptionData) Descriptor() ([]byte, []int) {
	return file_proto_parsers_inscription_proto_rawDescGZIP(), []int{0}
}

func (x *InscriptionData) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *InscriptionData) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *InscriptionData) GetParent() *parsepb.OutPoint {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *InscriptionData) GetScriptPrefix() []byte {
	if x != nil {
		return x.ScriptPrefix
	}
	return nil
}

func (x *InscriptionData) GetScriptSuffix() []byte {
	if x != nil {
		return x.ScriptSuffix
	}
	return nil
}

var File_proto_parsers_inscription_proto protoreflect.FileDescriptor

const file_proto_parsers_inscription_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/parsers/inscription.proto\x12\x0eonesat.parsers\x1a\x11proto/parse.proto\"\xc8\x01\n" +
	"\x0fInscriptionData\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12.\n" +
	"\x06parent\x18\x03 \x01(\v2\x16.onesat.parse.OutPointR\x06parent\x12#\n" +
	"\rscript_prefix\x18\x04 \x01(\fR\fscriptPrefix\x12#\n" +
	"\rscript_suffix\x18\x05 \x01(\fR\fscriptSuffixB0Z.github.com/b-open-io/1sat-engine/proto/parsersb\x06proto3"

var (
	file_proto_parsers_inscription_proto_rawDescOnce sync.Once
	file_proto_parsers_inscription_proto_rawDescData []byte
)

func file_proto_parsers_inscription_proto_rawDescGZIP() []byte {
	file_proto_parsers_inscription_proto_rawDescOnce.Do(func() {
		file_proto_parsers_inscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_parsers_inscription_proto_rawDesc), len(file_proto_parsers_inscription_proto_rawDesc)))
	})
	return file_proto_parsers_inscription_proto_rawDescData
}

var file_proto_parsers_inscription_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_parsers_inscription_proto_goTypes = []any{
	(*InscriptionData)(nil),  // 0: onesat.parsers.InscriptionData
	(*parsepb.OutPoint)(nil), // 1: onesat.parse.OutPoint
}
var file_proto_parsers_inscription_proto_depIdxs = []int32{
	1, // 0: onesat.parsers.InscriptionData.parent:type_name -> onesat.parse.OutPoint
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_parsers_inscription_proto_init() }
func file_proto_parsers_inscription_proto_init() {
	if File_proto_parsers_inscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_parsers_inscription_proto_rawDesc), len(file_proto_parsers_inscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_parsers_inscription_proto_goTypes,
		DependencyIndexes: file_proto_parsers_inscription_proto_depIdxs,
		MessageInfos:      file_proto_parsers_inscription_proto_msgTypes,
	}.Build()
	File_proto_parsers_inscription_proto = out.File
	file_proto_parsers_inscription_proto_goTypes = nil
	file_proto_parsers_inscription_proto_depIdxs = nil
}
