// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/parsers/ordlock.proto

package parsers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrdLockData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerPkhash  []byte                 `protobuf:"bytes,1,opt,name=seller_pkhash,json=sellerPkhash,proto3" json:"seller_pkhash,omitempty"` // 20 bytes
	Payout        []byte                 `protobuf:"bytes,2,opt,name=payout,proto3" json:"payout,omitempty"`                                 // raw payout script
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdLockData) Reset() {
	*x = OrdLockData{}
	mi := &file_proto_parsers_ordlock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdLockData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdLockData) ProtoMessage() {}

func (x *OrdLockData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsers_ordlock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdLockData.ProtoReflect.Descriptor instead.
func (*OrdLockData) Descriptor() ([]byte, []int) {
	return file_proto_parsers_ordlock_proto_rawDescGZIP(), []int{0}
}

func (x *OrdLockData) GetSellerPkhash() []byte {
	if x != nil {
		return x.SellerPkhash
	}
	return nil
}

func (x *OrdLockData) GetPayout() []byte {
	if x != nil {
		return x.Payout
	}
	return nil
}

var File_proto_parsers_ordlock_proto protoreflect.FileDescriptor

const file_proto_parsers_ordlock_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/parsers/ordlock.proto\x12\x0eonesat.parsers\"J\n" +
	"\vOrdLockData\x12#\n" +
	"\rseller_pkhash\x18\x01 \x01(\fR\fsellerPkhash\x12\x16\n" +
	"\x06payout\x18\x02 \x01(\fR\x06payoutB/Z-github.com/b-open-io/1sat-stack/proto/parsersb\x06proto3"

var (
	file_proto_parsers_ordlock_proto_rawDescOnce sync.Once
	file_proto_parsers_ordlock_proto_rawDescData []byte
)

func file_proto_parsers_ordlock_proto_rawDescGZIP() []byte {
	file_proto_parsers_ordlock_proto_rawDescOnce.Do(func() {
		file_proto_parsers_ordlock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_parsers_ordlock_proto_rawDesc), len(file_proto_parsers_ordlock_proto_rawDesc)))
	})
	return file_proto_parsers_ordlock_proto_rawDescData
}

var file_proto_parsers_ordlock_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_parsers_ordlock_proto_goTypes = []any{
	(*OrdLockData)(nil), // 0: onesat.parsers.OrdLockData
}
var file_proto_parsers_ordlock_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_parsers_ordlock_proto_init() }
func file_proto_parsers_ordlock_proto_init() {
	if File_proto_parsers_ordlock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_parsers_ordlock_proto_rawDesc), len(file_proto_parsers_ordlock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_parsers_ordlock_proto_goTypes,
		DependencyIndexes: file_proto_parsers_ordlock_proto_depIdxs,
		MessageInfos:      file_proto_parsers_ordlock_proto_msgTypes,
	}.Build()
	File_proto_parsers_ordlock_proto = out.File
	file_proto_parsers_ordlock_proto_goTypes = nil
	file_proto_parsers_ordlock_proto_depIdxs = nil
}
