// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: parse.proto

package parsepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          []byte                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"` // 32 bytes, internal byte order
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutPoint) Reset() {
	*x = OutPoint{}
	mi := &file_parse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutPoint) ProtoMessage() {}

func (x *OutPoint) ProtoReflect() protoreflect.Message {
	mi := &file_parse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutPoint.ProtoReflect.Descriptor instead.
func (*OutPoint) Descriptor() ([]byte, []int) {
	return file_parse_proto_rawDescGZIP(), []int{0}
}

func (x *OutPoint) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *OutPoint) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type IndexedOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outpoint      *OutPoint              `protobuf:"bytes,1,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	Satoshis      uint64                 `protobuf:"varint,2,opt,name=satoshis,proto3" json:"satoshis,omitempty"`
	BlockHeight   uint32                 `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	BlockIdx      uint64                 `protobuf:"varint,4,opt,name=block_idx,json=blockIdx,proto3" json:"block_idx,omitempty"`
	Events        []string               `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	Owners        [][]byte               `protobuf:"bytes,6,rep,name=owners,proto3" json:"owners,omitempty"`                        // each is 20-byte PKHash
	SpendTxid     []byte                 `protobuf:"bytes,7,opt,name=spend_txid,json=spendTxid,proto3" json:"spend_txid,omitempty"` // 32 bytes if spent, empty if not
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexedOutput) Reset() {
	*x = IndexedOutput{}
	mi := &file_parse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexedOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexedOutput) ProtoMessage() {}

func (x *IndexedOutput) ProtoReflect() protoreflect.Message {
	mi := &file_parse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexedOutput.ProtoReflect.Descriptor instead.
func (*IndexedOutput) Descriptor() ([]byte, []int) {
	return file_parse_proto_rawDescGZIP(), []int{1}
}

func (x *IndexedOutput) GetOutpoint() *OutPoint {
	if x != nil {
		return x.Outpoint
	}
	return nil
}

func (x *IndexedOutput) GetSatoshis() uint64 {
	if x != nil {
		return x.Satoshis
	}
	return 0
}

func (x *IndexedOutput) GetBlockHeight() uint32 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *IndexedOutput) GetBlockIdx() uint64 {
	if x != nil {
		return x.BlockIdx
	}
	return 0
}

func (x *IndexedOutput) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *IndexedOutput) GetOwners() [][]byte {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *IndexedOutput) GetSpendTxid() []byte {
	if x != nil {
		return x.SpendTxid
	}
	return nil
}

type BeefParseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*IndexedOutput       `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Spends        []*IndexedOutput       `protobuf:"bytes,2,rep,name=spends,proto3" json:"spends,omitempty"`
	Txid          []byte                 `protobuf:"bytes,3,opt,name=txid,proto3" json:"txid,omitempty"` // 32 bytes
	BlockHeight   uint32                 `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	BlockIdx      uint64                 `protobuf:"varint,5,opt,name=block_idx,json=blockIdx,proto3" json:"block_idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeefParseResult) Reset() {
	*x = BeefParseResult{}
	mi := &file_parse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeefParseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeefParseResult) ProtoMessage() {}

func (x *BeefParseResult) ProtoReflect() protoreflect.Message {
	mi := &file_parse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeefParseResult.ProtoReflect.Descriptor instead.
func (*BeefParseResult) Descriptor() ([]byte, []int) {
	return file_parse_proto_rawDescGZIP(), []int{2}
}

func (x *BeefParseResult) GetOutputs() []*IndexedOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *BeefParseResult) GetSpends() []*IndexedOutput {
	if x != nil {
		return x.Spends
	}
	return nil
}

func (x *BeefParseResult) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *BeefParseResult) GetBlockHeight() uint32 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *BeefParseResult) GetBlockIdx() uint64 {
	if x != nil {
		return x.BlockIdx
	}
	return 0
}

var File_parse_proto protoreflect.FileDescriptor

const file_parse_proto_rawDesc = "" +
	"\n" +
	"\vparse.proto\x12\fonesat.parse\"4\n" +
	"\bOutPoint\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\fR\x04txid\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"\xee\x01\n" +
	"\rIndexedOutput\x122\n" +
	"\boutpoint\x18\x01 \x01(\v2\x16.onesat.parse.OutPointR\boutpoint\x12\x1a\n" +
	"\bsatoshis\x18\x02 \x01(\x04R\bsatoshis\x12!\n" +
	"\fblock_height\x18\x03 \x01(\rR\vblockHeight\x12\x1b\n" +
	"\tblock_idx\x18\x04 \x01(\x04R\bblockIdx\x12\x16\n" +
	"\x06events\x18\x05 \x03(\tR\x06events\x12\x16\n" +
	"\x06owners\x18\x06 \x03(\fR\x06owners\x12\x1d\n" +
	"\n" +
	"spend_txid\x18\a \x01(\fR\tspendTxid\"\xd1\x01\n" +
	"\x0fBeefParseResult\x125\n" +
	"\aoutputs\x18\x01 \x03(\v2\x1b.onesat.parse.IndexedOutputR\aoutputs\x123\n" +
	"\x06spends\x18\x02 \x03(\v2\x1b.onesat.parse.IndexedOutputR\x06spends\x12\x12\n" +
	"\x04txid\x18\x03 \x01(\fR\x04txid\x12!\n" +
	"\fblock_height\x18\x04 \x01(\rR\vblockHeight\x12\x1b\n" +
	"\tblock_idx\x18\x05 \x01(\x04R\bblockIdxB/Z-github.com/b-open-io/1sat-stack/proto/parsepbb\x06proto3"

var (
	file_parse_proto_rawDescOnce sync.Once
	file_parse_proto_rawDescData []byte
)

func file_parse_proto_rawDescGZIP() []byte {
	file_parse_proto_rawDescOnce.Do(func() {
		file_parse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parse_proto_rawDesc), len(file_parse_proto_rawDesc)))
	})
	return file_parse_proto_rawDescData
}

var file_parse_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_parse_proto_goTypes = []any{
	(*OutPoint)(nil),        // 0: onesat.parse.OutPoint
	(*IndexedOutput)(nil),   // 1: onesat.parse.IndexedOutput
	(*BeefParseResult)(nil), // 2: onesat.parse.BeefParseResult
}
var file_parse_proto_depIdxs = []int32{
	0, // 0: onesat.parse.IndexedOutput.outpoint:type_name -> onesat.parse.OutPoint
	1, // 1: onesat.parse.BeefParseResult.outputs:type_name -> onesat.parse.IndexedOutput
	1, // 2: onesat.parse.BeefParseResult.spends:type_name -> onesat.parse.IndexedOutput
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_parse_proto_init() }
func file_parse_proto_init() {
	if File_parse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parse_proto_rawDesc), len(file_parse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parse_proto_goTypes,
		DependencyIndexes: file_parse_proto_depIdxs,
		MessageInfos:      file_parse_proto_msgTypes,
	}.Build()
	File_parse_proto = out.File
	file_parse_proto_goTypes = nil
	file_parse_proto_depIdxs = nil
}
