// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/beef.proto

package beefpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataFormat int32

const (
	DataFormat_RAW_TX                DataFormat = 0
	DataFormat_RAW_TX_AND_BUMP_INDEX DataFormat = 1
	DataFormat_TXID_ONLY             DataFormat = 2
)

// Enum value maps for DataFormat.
var (
	DataFormat_name = map[int32]string{
		0: "RAW_TX",
		1: "RAW_TX_AND_BUMP_INDEX",
		2: "TXID_ONLY",
	}
	DataFormat_value = map[string]int32{
		"RAW_TX":                0,
		"RAW_TX_AND_BUMP_INDEX": 1,
		"TXID_ONLY":             2,
	}
)

func (x DataFormat) Enum() *DataFormat {
	p := new(DataFormat)
	*p = x
	return p
}

func (x DataFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_beef_proto_enumTypes[0].Descriptor()
}

func (DataFormat) Type() protoreflect.EnumType {
	return &file_proto_beef_proto_enumTypes[0]
}

func (x DataFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataFormat.Descriptor instead.
func (DataFormat) EnumDescriptor() ([]byte, []int) {
	return file_proto_beef_proto_rawDescGZIP(), []int{0}
}

type BeefTx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          []byte                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	DataFormat    DataFormat             `protobuf:"varint,2,opt,name=data_format,json=dataFormat,proto3,enum=onesat.beef.DataFormat" json:"data_format,omitempty"`
	RawTx         []byte                 `protobuf:"bytes,3,opt,name=raw_tx,json=rawTx,proto3" json:"raw_tx,omitempty"`
	BumpIndex     *uint32                `protobuf:"varint,4,opt,name=bump_index,json=bumpIndex,proto3,oneof" json:"bump_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeefTx) Reset() {
	*x = BeefTx{}
	mi := &file_proto_beef_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeefTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeefTx) ProtoMessage() {}

func (x *BeefTx) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beef_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeefTx.ProtoReflect.Descriptor instead.
func (*BeefTx) Descriptor() ([]byte, []int) {
	return file_proto_beef_proto_rawDescGZIP(), []int{0}
}

func (x *BeefTx) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *BeefTx) GetDataFormat() DataFormat {
	if x != nil {
		return x.DataFormat
	}
	return DataFormat_RAW_TX
}

func (x *BeefTx) GetRawTx() []byte {
	if x != nil {
		return x.RawTx
	}
	return nil
}

func (x *BeefTx) GetBumpIndex() uint32 {
	if x != nil && x.BumpIndex != nil {
		return *x.BumpIndex
	}
	return 0
}

type Beef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bumps         []*MerklePath          `protobuf:"bytes,1,rep,name=bumps,proto3" json:"bumps,omitempty"`
	Transactions  []*BeefTx              `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Beef) Reset() {
	*x = Beef{}
	mi := &file_proto_beef_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Beef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beef) ProtoMessage() {}

func (x *Beef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beef_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beef.ProtoReflect.Descriptor instead.
func (*Beef) Descriptor() ([]byte, []int) {
	return file_proto_beef_proto_rawDescGZIP(), []int{1}
}

func (x *Beef) GetBumps() []*MerklePath {
	if x != nil {
		return x.Bumps
	}
	return nil
}

func (x *Beef) GetTransactions() []*BeefTx {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type AtomicBeef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          []byte                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"` // 32 bytes, target transaction
	Beef          *Beef                  `protobuf:"bytes,2,opt,name=beef,proto3" json:"beef,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtomicBeef) Reset() {
	*x = AtomicBeef{}
	mi := &file_proto_beef_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtomicBeef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicBeef) ProtoMessage() {}

func (x *AtomicBeef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beef_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicBeef.ProtoReflect.Descriptor instead.
func (*AtomicBeef) Descriptor() ([]byte, []int) {
	return file_proto_beef_proto_rawDescGZIP(), []int{2}
}

func (x *AtomicBeef) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *AtomicBeef) GetBeef() *Beef {
	if x != nil {
		return x.Beef
	}
	return nil
}

type MerklePath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeight   uint32                 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Path          []*PathLevel           `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerklePath) Reset() {
	*x = MerklePath{}
	mi := &file_proto_beef_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerklePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerklePath) ProtoMessage() {}

func (x *MerklePath) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beef_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerklePath.ProtoReflect.Descriptor instead.
func (*MerklePath) Descriptor() ([]byte, []int) {
	return file_proto_beef_proto_rawDescGZIP(), []int{3}
}

func (x *MerklePath) GetBlockHeight() uint32 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *MerklePath) GetPath() []*PathLevel {
	if x != nil {
		return x.Path
	}
	return nil
}

type PathLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*PathElement         `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathLevel) Reset() {
	*x = PathLevel{}
	mi := &file_proto_beef_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathLevel) ProtoMessage() {}

func (x *PathLevel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beef_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathLevel.ProtoReflect.Descriptor instead.
func (*PathLevel) Descriptor() ([]byte, []int) {
	return file_proto_beef_proto_rawDescGZIP(), []int{4}
}

func (x *PathLevel) GetElements() []*PathElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

type PathElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Txid          bool                   `protobuf:"varint,3,opt,name=txid,proto3" json:"txid,omitempty"`
	Duplicate     bool                   `protobuf:"varint,4,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathElement) Reset() {
	*x = PathElement{}
	mi := &file_proto_beef_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathElement) ProtoMessage() {}

func (x *PathElement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beef_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathElement.ProtoReflect.Descriptor instead.
func (*PathElement) Descriptor() ([]byte, []int) {
	return file_proto_beef_proto_rawDescGZIP(), []int{5}
}

func (x *PathElement) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PathElement) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *PathElement) GetTxid() bool {
	if x != nil {
		return x.Txid
	}
	return false
}

func (x *PathElement) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

var File_proto_beef_proto protoreflect.FileDescriptor

const file_proto_beef_proto_rawDesc = "" +
	"\n" +
	"\x10proto/beef.proto\x12\vonesat.beef\"\xa0\x01\n" +
	"\x06BeefTx\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\fR\x04txid\x128\n" +
	"\vdata_format\x18\x02 \x01(\x0e2\x17.onesat.beef.DataFormatR\n" +
	"dataFormat\x12\x15\n" +
	"\x06raw_tx\x18\x03 \x01(\fR\x05rawTx\x12\"\n" +
	"\n" +
	"bump_index\x18\x04 \x01(\rH\x00R\tbumpIndex\x88\x01\x01B\r\n" +
	"\v_bump_index\"n\n" +
	"\x04Beef\x12-\n" +
	"\x05bumps\x18\x01 \x03(\v2\x17.onesat.beef.MerklePathR\x05bumps\x127\n" +
	"\ftransactions\x18\x02 \x03(\v2\x13.onesat.beef.BeefTxR\ftransactions\"G\n" +
	"\n" +
	"AtomicBeef\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\fR\x04txid\x12%\n" +
	"\x04beef\x18\x02 \x01(\v2\x11.onesat.beef.BeefR\x04beef\"[\n" +
	"\n" +
	"MerklePath\x12!\n" +
	"\fblock_height\x18\x01 \x01(\rR\vblockHeight\x12*\n" +
	"\x04path\x18\x02 \x03(\v2\x16.onesat.beef.PathLevelR\x04path\"A\n" +
	"\tPathLevel\x124\n" +
	"\belements\x18\x01 \x03(\v2\x18.onesat.beef.PathElementR\belements\"k\n" +
	"\vPathElement\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x12\n" +
	"\x04txid\x18\x03 \x01(\bR\x04txid\x12\x1c\n" +
	"\tduplicate\x18\x04 \x01(\bR\tduplicate*B\n" +
	"\n" +
	"DataFormat\x12\n" +
	"\n" +
	"\x06RAW_TX\x10\x00\x12\x19\n" +
	"\x15RAW_TX_AND_BUMP_INDEX\x10\x01\x12\r\n" +
	"\tTXID_ONLY\x10\x02B/Z-github.com/b-open-io/1sat-engine/proto/beefpbb\x06proto3"

var (
	file_proto_beef_proto_rawDescOnce sync.Once
	file_proto_beef_proto_rawDescData []byte
)

func file_proto_beef_proto_rawDescGZIP() []byte {
	file_proto_beef_proto_rawDescOnce.Do(func() {
		file_proto_beef_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_beef_proto_rawDesc), len(file_proto_beef_proto_rawDesc)))
	})
	return file_proto_beef_proto_rawDescData
}

var file_proto_beef_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_beef_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_beef_proto_goTypes = []any{
	(DataFormat)(0),     // 0: onesat.beef.DataFormat
	(*BeefTx)(nil),      // 1: onesat.beef.BeefTx
	(*Beef)(nil),        // 2: onesat.beef.Beef
	(*AtomicBeef)(nil),  // 3: onesat.beef.AtomicBeef
	(*MerklePath)(nil),  // 4: onesat.beef.MerklePath
	(*PathLevel)(nil),   // 5: onesat.beef.PathLevel
	(*PathElement)(nil), // 6: onesat.beef.PathElement
}
var file_proto_beef_proto_depIdxs = []int32{
	0, // 0: onesat.beef.BeefTx.data_format:type_name -> onesat.beef.DataFormat
	4, // 1: onesat.beef.Beef.bumps:type_name -> onesat.beef.MerklePath
	1, // 2: onesat.beef.Beef.transactions:type_name -> onesat.beef.BeefTx
	2, // 3: onesat.beef.AtomicBeef.beef:type_name -> onesat.beef.Beef
	5, // 4: onesat.beef.MerklePath.path:type_name -> onesat.beef.PathLevel
	6, // 5: onesat.beef.PathLevel.elements:type_name -> onesat.beef.PathElement
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_beef_proto_init() }
func file_proto_beef_proto_init() {
	if File_proto_beef_proto != nil {
		return
	}
	file_proto_beef_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_beef_proto_rawDesc), len(file_proto_beef_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_beef_proto_goTypes,
		DependencyIndexes: file_proto_beef_proto_depIdxs,
		EnumInfos:         file_proto_beef_proto_enumTypes,
		MessageInfos:      file_proto_beef_proto_msgTypes,
	}.Build()
	File_proto_beef_proto = out.File
	file_proto_beef_proto_goTypes = nil
	file_proto_beef_proto_depIdxs = nil
}
