// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/b-open-io/1sat-stack"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/arc/callback": {
            "post": {
                "description": "Receives transaction status updates from Arc broadcaster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "merkle"
                ],
                "summary": "Handle Arc callback",
                "parameters": [
                    {
                        "description": "Arc callback payload",
                        "name": "callback",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merkle.ArcCallback"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/beef/{txid}": {
            "get": {
                "description": "Retrieves the BEEF (BSV Envelope Format) for a specific transaction",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "beef"
                ],
                "summary": "Get BEEF for a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "txid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "BEEF bytes",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Transaction not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/beef/{txid}/proof": {
            "get": {
                "description": "Retrieves just the merkle proof bytes for a transaction",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "beef"
                ],
                "summary": "Get merkle proof",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "txid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Merkle proof bytes",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Proof not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/beef/{txid}/raw": {
            "get": {
                "description": "Retrieves just the raw transaction bytes (without proof)",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "beef"
                ],
                "summary": "Get raw transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "txid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Raw transaction bytes",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Transaction not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/bsv21/{tokenId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bsv21"
                ],
                "summary": "Get BSV21 token details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token ID (outpoint format: txid_vout)",
                        "name": "tokenId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_bsv21.TokenResponse"
                        }
                    }
                }
            }
        },
        "/bsv21/{tokenId}/block/{height}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bsv21"
                ],
                "summary": "Get block data for a token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token ID",
                        "name": "tokenId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Block height",
                        "name": "height",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_bsv21.BlockResponse"
                        }
                    }
                }
            }
        },
        "/bsv21/{tokenId}/tx/{txid}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bsv21"
                ],
                "summary": "Get transaction details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token ID",
                        "name": "tokenId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "txid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Include BEEF data",
                        "name": "beef",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/bsv21/{tokenId}/{lockType}/balance": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bsv21"
                ],
                "summary": "Get multi-address token balance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token ID",
                        "name": "tokenId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Lock type",
                        "name": "lockType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Array of addresses (max 100)",
                        "name": "addresses",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_bsv21.BalanceResponse"
                        }
                    }
                }
            }
        },
        "/bsv21/{tokenId}/{lockType}/history": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bsv21"
                ],
                "summary": "Get multi-address transaction history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token ID",
                        "name": "tokenId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Lock type",
                        "name": "lockType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Array of addresses (max 100)",
                        "name": "addresses",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_txo.IndexedOutput"
                            }
                        }
                    }
                }
            }
        },
        "/bsv21/{tokenId}/{lockType}/unspent": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bsv21"
                ],
                "summary": "Get multi-address unspent outputs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token ID",
                        "name": "tokenId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Lock type",
                        "name": "lockType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Array of addresses (max 100)",
                        "name": "addresses",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_txo.IndexedOutput"
                            }
                        }
                    }
                }
            }
        },
        "/bsv21/{tokenId}/{lockType}/{address}/balance": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bsv21"
                ],
                "summary": "Get address token balance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token ID",
                        "name": "tokenId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Lock type (p2pkh, cos, list, etc.)",
                        "name": "lockType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_bsv21.BalanceResponse"
                        }
                    }
                }
            }
        },
        "/bsv21/{tokenId}/{lockType}/{address}/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bsv21"
                ],
                "summary": "Get address transaction history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token ID",
                        "name": "tokenId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Lock type",
                        "name": "lockType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_txo.IndexedOutput"
                            }
                        }
                    }
                }
            }
        },
        "/bsv21/{tokenId}/{lockType}/{address}/unspent": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bsv21"
                ],
                "summary": "Get address unspent outputs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token ID",
                        "name": "tokenId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Lock type",
                        "name": "lockType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_txo.IndexedOutput"
                            }
                        }
                    }
                }
            }
        },
        "/indexer/parse": {
            "post": {
                "description": "Parses a transaction from raw bytes and returns the indexed context without saving",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "indexer"
                ],
                "summary": "Parse a transaction from raw bytes",
                "parameters": [
                    {
                        "description": "Raw transaction bytes",
                        "name": "tx",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_indexer.IndexContext"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/indexer/tags": {
            "get": {
                "description": "Returns the list of tags from all registered indexers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "indexer"
                ],
                "summary": "Get available indexer tags",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/indexer/{txid}/ingest": {
            "post": {
                "description": "Ingests a transaction by txid, parsing and saving to the store",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "indexer"
                ],
                "summary": "Ingest a transaction by txid",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "txid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_indexer.IndexContext"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/indexer/{txid}/parse": {
            "get": {
                "description": "Parses a transaction and returns the indexed context without saving",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "indexer"
                ],
                "summary": "Parse a transaction by txid",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "txid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_indexer.IndexContext"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ordfs/content/{path}": {
            "get": {
                "description": "Serve the content of an inscription by outpoint or txid",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "ordfs"
                ],
                "summary": "Get inscription content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Outpoint (txid_vout) or txid",
                        "name": "path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ordfs/metadata/{path}": {
            "get": {
                "description": "Get metadata about inscription content without downloading the content",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ordfs"
                ],
                "summary": "Get content metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Outpoint (txid_vout) or txid",
                        "name": "path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Metadata",
                        "schema": {
                            "$ref": "#/definitions/pkg_ordfs.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ordfs/output/{path}": {
            "get": {
                "description": "Get the raw transaction output bytes",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "ordfs"
                ],
                "summary": "Get raw output",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Outpoint (txid_vout) or txid",
                        "name": "path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Output bytes",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sse/{topics}": {
            "get": {
                "description": "Establishes an SSE connection for real-time event streaming",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "sse"
                ],
                "summary": "Subscribe to Server-Sent Events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated list of topics to subscribe to",
                        "name": "topics",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "engine.MerkleState": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "MerkleStateUnmined",
                "MerkleStateValidated",
                "MerkleStateInvalidated",
                "MerkleStateImmutable"
            ]
        },
        "github_com_b-open-io_1sat-stack_pkg_bsv21.BalanceResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "utxoCount": {
                    "type": "integer"
                }
            }
        },
        "github_com_b-open-io_1sat-stack_pkg_bsv21.BlockInfo": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "previousblockhash": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "github_com_b-open-io_1sat-stack_pkg_bsv21.BlockResponse": {
            "type": "object",
            "properties": {
                "block": {
                    "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_bsv21.BlockInfo"
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_txo.TransactionData"
                    }
                }
            }
        },
        "github_com_b-open-io_1sat-stack_pkg_bsv21.TokenResponse": {
            "type": "object",
            "properties": {
                "amt": {
                    "type": "string"
                },
                "dec": {
                    "type": "integer"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "op": {
                    "type": "string"
                },
                "sym": {
                    "type": "string"
                },
                "txid": {
                    "type": "string"
                },
                "vout": {
                    "type": "integer"
                }
            }
        },
        "github_com_b-open-io_1sat-stack_pkg_indexer.IndexContext": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "idx": {
                    "type": "integer"
                },
                "outputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_txo.IndexedOutput"
                    }
                },
                "score": {
                    "type": "number"
                },
                "spends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_txo.IndexedOutput"
                    }
                },
                "txid": {
                    "type": "string"
                }
            }
        },
        "github_com_b-open-io_1sat-stack_pkg_ordfs.Response": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "contentLength": {
                    "type": "integer"
                },
                "contentType": {
                    "type": "string"
                },
                "map": {
                    "description": "JSON string",
                    "type": "string"
                },
                "origin": {
                    "$ref": "#/definitions/transaction.Outpoint"
                },
                "outpoint": {
                    "$ref": "#/definitions/transaction.Outpoint"
                },
                "output": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "parent": {
                    "$ref": "#/definitions/transaction.Outpoint"
                },
                "sequence": {
                    "type": "integer"
                }
            }
        },
        "github_com_b-open-io_1sat-stack_pkg_txo.IndexedOutput": {
            "type": "object",
            "properties": {
                "ancillaryTxids": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "beef": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "blockHeight": {
                    "type": "integer",
                    "format": "int32"
                },
                "blockIdx": {
                    "type": "integer",
                    "format": "int64"
                },
                "consumedBy": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/transaction.Outpoint"
                    }
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "events": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "merkleRoot": {
                    "description": "Merkle root extracted from the merkle path",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "merkleState": {
                    "description": "Validation state of the merkle proof",
                    "allOf": [
                        {
                            "$ref": "#/definitions/engine.MerkleState"
                        }
                    ]
                },
                "outpoint": {
                    "$ref": "#/definitions/transaction.Outpoint"
                },
                "outputsConsumed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/transaction.Outpoint"
                    }
                },
                "owners": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer",
                            "format": "int32"
                        }
                    }
                },
                "satoshis": {
                    "description": "Extended fields for indexing",
                    "type": "integer"
                },
                "score": {
                    "description": "sort score for outputs. Usage is up to Storage implementation.",
                    "type": "number",
                    "format": "float64"
                },
                "spend": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "spent": {
                    "type": "boolean"
                },
                "topic": {
                    "type": "string"
                }
            }
        },
        "github_com_b-open-io_1sat-stack_pkg_txo.TransactionData": {
            "type": "object",
            "properties": {
                "beef": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "block_height": {
                    "type": "integer"
                },
                "block_index": {
                    "type": "integer"
                },
                "inputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_txo.IndexedOutput"
                    }
                },
                "outputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_txo.IndexedOutput"
                    }
                },
                "txid": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "merkle.ArcCallback": {
            "type": "object",
            "properties": {
                "merklePath": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "txId": {
                    "type": "string"
                },
                "txStatus": {
                    "type": "string"
                }
            }
        },
        "pkg_bsv21.BalanceResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "utxoCount": {
                    "type": "integer"
                }
            }
        },
        "pkg_bsv21.BlockInfo": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "previousblockhash": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "pkg_bsv21.BlockResponse": {
            "type": "object",
            "properties": {
                "block": {
                    "$ref": "#/definitions/pkg_bsv21.BlockInfo"
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_txo.TransactionData"
                    }
                }
            }
        },
        "pkg_bsv21.TokenResponse": {
            "type": "object",
            "properties": {
                "amt": {
                    "type": "string"
                },
                "dec": {
                    "type": "integer"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "op": {
                    "type": "string"
                },
                "sym": {
                    "type": "string"
                },
                "txid": {
                    "type": "string"
                },
                "vout": {
                    "type": "integer"
                }
            }
        },
        "pkg_indexer.IndexContext": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "idx": {
                    "type": "integer"
                },
                "outputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_txo.IndexedOutput"
                    }
                },
                "score": {
                    "type": "number"
                },
                "spends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_b-open-io_1sat-stack_pkg_txo.IndexedOutput"
                    }
                },
                "txid": {
                    "type": "string"
                }
            }
        },
        "pkg_ordfs.Response": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "contentLength": {
                    "type": "integer"
                },
                "contentType": {
                    "type": "string"
                },
                "map": {
                    "description": "JSON string",
                    "type": "string"
                },
                "origin": {
                    "$ref": "#/definitions/transaction.Outpoint"
                },
                "outpoint": {
                    "$ref": "#/definitions/transaction.Outpoint"
                },
                "output": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "parent": {
                    "$ref": "#/definitions/transaction.Outpoint"
                },
                "sequence": {
                    "type": "integer"
                }
            }
        },
        "transaction.Outpoint": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer"
                },
                "txid": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "1Sat Stack API",
	Description:      "Composable BSV blockchain services API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
